# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    container_name: db_mongo-maintenance
    restart: always
    ports:
      - 27018:27017
    env_file: "/opt/droids/4-A7-maintenance/deploy/.env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - holonet-maintenance

  mongo-express:
    image: mongo-express
    container_name: db_mongo-express-maintenance
    restart: always
    ports:
      - 9082:8081
    env_file: "/opt/droids/4-A7-maintenance/deploy/.env"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    networks:
      - holonet-maintenance

networks:
  holonet-maintenance:
    external: true
