version: "3"
name: 4-a7-maintenance
services:
  xwsbot:
    image: docker.io/sogemoge/4-a7-maintenance:latest
    container_name: inventory_droid_on_maintenance
    environment:
      - COMPOSE_PROJECT_NAME
    restart: always
    ports:
      - 0.0.0.0:8091:801
    volumes:
      - /opt/droids/4-A7-maintenance/deploy/bot/.env:/opt/4-A7/.env:Z
      - /opt/droids/4-A7-maintenance/submodules/xwing-data2:/opt/4-A7/xwing-data2
      - /opt/droids/4-A7-maintenance/xwsbot.log:/opt/4-A7/xwsbot.log:Z
